name: not_defterim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0 
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  http: ^1.2.0  # Added for Book Search functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

# --- APP ICON CONFIGURATION ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tortul_logo.jpeg" 
  min_sdk_android: 21 
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/tortul_logo.jpeg"